name: Slack Test
on:
  workflow_dispatch:
jobs:
  slack_upload_job:
    runs-on: ubuntu-latest
    name: Upload test file
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - run: mkdir upload
      - run: echo "Test file " > upload/test.txt
      - run: echo "Test file " > upload/test2.txt
      - run: zip -r report.zip upload
      - name: Upload to slack step
        uses: adrey/slack-file-upload-action@master
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          path: report.zip
          channel: gh-actions